-- check the null values in each column
SELECT 	 SUM(CASE WHEN invoice_and_item_number IS NULL THEN 1 ELSE 0 END),
		 SUM(CASE WHEN date IS NULL THEN 1 ELSE 0 END),
		 SUM(CASE WHEN store_number IS NULL THEN 1 ELSE 0 END),
		 SUM(CASE WHEN store_name IS NULL THEN 1 ELSE 0 END),
		 SUM(CASE WHEN address IS NULL THEN 1 ELSE 0 END),
		 SUM(CASE WHEN city IS NULL THEN 1 ELSE 0 END),
		 SUM(CASE WHEN zip_code IS NULL THEN 1 ELSE 0 END),
		 SUM(CASE WHEN store_location IS NULL THEN 1 ELSE 0 END),
		 SUM(CASE WHEN county_number IS NULL THEN 1 ELSE 0 END),
		 SUM(CASE WHEN county IS NULL THEN 1 ELSE 0 END),
		 SUM(CASE WHEN category IS NULL THEN 1 ELSE 0 END),
		 SUM(CASE WHEN category_name IS NULL THEN 1 ELSE 0 END),
		 SUM(CASE WHEN vendor_number IS NULL THEN 1 ELSE 0 END),
		 SUM(CASE WHEN vendor_name IS NULL THEN 1 ELSE 0 END),
		 SUM(CASE WHEN item_number IS NULL THEN 1 ELSE 0 END),
		 SUM(CASE WHEN item_description IS NULL THEN 1 ELSE 0 END),
		 SUM(CASE WHEN pack IS NULL THEN 1 ELSE 0 END),
		 SUM(CASE WHEN bottle_volume_ml IS NULL THEN 1 ELSE 0 END),
		 SUM(CASE WHEN state_bottle_cost  IS NULL THEN 1 ELSE 0 END),
		 SUM(CASE WHEN state_bottle_retail  IS NULL THEN 1 ELSE 0 END),
		 SUM(CASE WHEN bottles_sold  IS NULL THEN 1 ELSE 0 END),
		 SUM(CASE WHEN sale_dollars  IS NULL THEN 1 ELSE 0 END),
		 SUM(CASE WHEN volume_sold_liters  IS NULL THEN 1 ELSE 0 END),
		 SUM(CASE WHEN volume_sold_gallons IS NULL THEN 1 ELSE 0 END)
FROM iowa_drink_sales;
